### ISSUE TITLE
Upgrading from 0.12 to 0.13 isn't source compatible

### ISSUE THREAD

**Issue by Feelemoon** [eclipse-paho/paho.mqtt.rust#240]
After upgrading to 0.13, my source does not compile anymore, as this change isn't backwards compatible. In example:

```
error[E0277]: `MqttVersion` doesn't implement `std::fmt::Display`
```

Could you implement `std::fmt::Display` for the newly introduced types?

**Comment by fpagliughi** [comment]
Yes. This is a major version upgrade, which allows for breaking API changes. (For versions less than 1.0, the minor version indicates a breaking change).

That said, `MQTTVersion` and the other new enumerations should probably implement the _Display_ trait!

Thanks for pointing it out.

**Comment by fpagliughi** [comment]
Added to v0.13.1
